FROM ubuntu 
MAINTAINER kensuke-mi <kensuke.mit@gmail.com>

RUN apt-get update
RUN apt-get install -y gcc-5 g++-5
RUN apt-get install -y git
RUN apt-get install -y make
RUN apt-get install -y openssl libssl-dev libbz2-dev libreadline-dev libsqlite3-dev
RUN apt-get install -y python3
RUN apt-get install -y python-setuptools python-pip
RUN apt-get install -y gedit
RUN apt-get install -y xz-utils
RUN apt-get install -y vim
