set encoding=utf-8
set nocompatible               " be iMproved
filetype off
"Setting for python
autocmd FileType python setl autoindent
autocmd FileType python setl smartindent cinwords=if,elif,else,for,while,try,except,finally,def,class
autocmd FileType python setl tabstop=8 expandtab shiftwidth=4 softtabstop=4

if has('vim_starting')
  set runtimepath+=~/.vim/bundle/neobundle.vim
  call neobundle#rc(expand('~/.vim/bundle/'))
endif
" originalrepos on github
NeoBundle 'Shougo/neobundle.vim'
NeoBundle 'Shougo/vimproc'
NeoBundle 'VimClojure'
NeoBundle 'Shougo/vimshell'
NeoBundle 'Shougo/unite.vim'
NeoBundle 'Shougo/neocomplcache'
NeoBundle 'Shougo/neosnippet'
NeoBundle 'jpalardy/vim-slime'
NeoBundle 'scrooloose/syntastic'
NeoBundle 'davidhalter/jedi-vim'
NeoBundle 'hynek/vim-python-pep8-indent'
NeoBundle 'taglist.vim'
NeoBundle 'Yggdroot/indentLine'
NeoBundle 'scrooloose/nerdtree'
NeoBundle 'jmcantrell/vim-virtualenv'
""NeoBundle 'https://bitbucket.org/kovisoft/slimv'

"" neocomplcache
let g:neocomplcache_enable_at_startup = 1
let g:neocomplcache_enable_smart_case = 1
let g:neocomplcache_enable_camel_case = 1
let g:neocomplcache_max_list = 40
let g:neocomplcache_auto_completion_start_length = 2

"" jedi-vim
let g:jedi#popup_on_dot = 0
let g:jedi#auto_initialization = 1
let g:jedi#rename_command = "<leader>R"
autocmd FileType python let b:did_ftplugin = 1

filetype plugin indent on     " required!
filetype indent on
syntax on


