export PATH=/opt/local/bin:/opt/local/sbin/:$PATH
export MANPATH=/opt/local/man:$MANPATH
export PATH=$PATH:/Users/mi-ssawa/bin/
export PATH=$PATH:/Applications/MacVim-snapshot-66/
export PYTHONPATH=/Library/Python/2.7/site-packages/:$PYTHONPATH
alias sgnuplot="/Applications/Gnuplot.app/Contents/Resources/bin/gnuplot"
alias octave="/Applications/Octave.app/Contents/Resources/bin/octave"
export GNUTERM=x11

#For auto-completion of git system
source ~/.git-completion.bash
